/**
 * Service Registry
 *
 * Each service defines:
 *   id             - unique identifier (used in URL params)
 *   name           - display name
 *   category       - grouping label
 *   color          - brand color for avatar
 *   statusPageUrl  - public status page link
 *   apiUrl         - machine-readable status endpoint
 *   type           - parser type: 'statuspage' | 'slack' | 'google_cloud'
 *   regionFilter   - (optional) filter incidents by region
 *     .exclude     - array of component name patterns to ignore
 *                    An incident is hidden if ALL its affected components
 *                    match one of these patterns (case-insensitive).
 *                    Example: { exclude: ['Middle East', 'APAC'] }
 *
 * To add a new service, append an entry here and (if needed) add
 * a parser in statusChecker.js.
 */

const services = [
  // --- E-Commerce ---
  {
    id: 'shopify',
    name: 'Shopify',
    category: 'E-Commerce',
    popular: true,
    color: '#96bf48',
    statusPageUrl: 'https://status.shopify.com',
    apiUrl: 'https://status.shopify.com/api/v2/status.json',
    type: 'statuspage',
  },
  {
    id: 'klaviyo',
    name: 'Klaviyo',
    category: 'E-Commerce',
    color: '#1c1c1c',
    statusPageUrl: 'https://status.klaviyo.com',
    apiUrl: 'https://status.klaviyo.com/api/v2/status.json',
    type: 'statuspage',
  },
  {
    id: 'recharge',
    name: 'Recharge',
    category: 'E-Commerce',
    color: '#5433ff',
    statusPageUrl: 'https://status.rechargepayments.com',
    apiUrl: 'https://status.rechargepayments.com/api/v2/status.json',
    type: 'statuspage',
  },
  {
    id: 'bigcommerce',
    name: 'BigCommerce',
    category: 'E-Commerce',
    color: '#34313f',
    statusPageUrl: 'https://status.bigcommerce.com',
    apiUrl: 'https://status.bigcommerce.com/api/v2/status.json',
    type: 'statuspage',
  },
  {
    id: 'squarespace',
    name: 'Squarespace',
    category: 'E-Commerce',
    color: '#000000',
    statusPageUrl: 'https://status.squarespace.com',
    apiUrl: 'https://status.squarespace.com/api/v2/status.json',
    type: 'statuspage',
  },
  {
    id: 'webflow',
    name: 'Webflow',
    category: 'E-Commerce',
    color: '#4353ff',
    statusPageUrl: 'https://status.webflow.com',
    apiUrl: 'https://status.webflow.com/api/v2/status.json',
    type: 'statuspage',
  },

  // --- Payments ---
  {
    id: 'stripe',
    popular: true,
    name: 'Stripe',
    category: 'Payments',
    color: '#6772e5',
    statusPageUrl: 'https://status.stripe.com',
    apiUrl: 'https://status.stripe.com/api/v2/status.json',
    type: 'statuspage',
  },
  {
    id: 'plaid',
    name: 'Plaid',
    category: 'Payments',
    color: '#00b25a',
    statusPageUrl: 'https://status.plaid.com',
    apiUrl: 'https://status.plaid.com/api/v2/status.json',
    type: 'statuspage',
  },
  {
    id: 'chargebee',
    name: 'Chargebee',
    category: 'Payments',
    color: '#ff6c37',
    statusPageUrl: 'https://status.chargebee.com',
    apiUrl: 'https://status.chargebee.com/api/v2/status.json',
    type: 'statuspage',
  },
  {
    id: 'braintree',
    name: 'Braintree',
    category: 'Payments',
    color: '#3d95ce',
    logoDomain: 'braintree.com',
    statusPageUrl: 'https://status.braintreepayments.com',
    apiUrl: 'https://status.braintreepayments.com/api/v2/status.json',
    type: 'statuspage',
  },
  {
    id: 'paypal',
    name: 'PayPal',
    category: 'Payments',
    color: '#003087',
    logoDomain: 'paypal.com',
    statusPageUrl: 'https://www.paypal-status.com',
    apiUrl: 'https://www.paypal-status.com/api/v2/status.json',
    type: 'statuspage',
  },

  // --- AI ---
  {
    id: 'claude',
    popular: true,
    name: 'Claude',
    category: 'AI',
    color: '#d97757',
    logoDomain: 'claude.ai',
    statusPageUrl: 'https://status.anthropic.com',
    apiUrl: 'https://status.anthropic.com/api/v2/status.json',
    type: 'statuspage',
  },
  {
    id: 'openai',
    popular: true,
    name: 'OpenAI',
    category: 'AI',
    color: '#10a37f',
    statusPageUrl: 'https://status.openai.com',
    apiUrl: 'https://status.openai.com/api/v2/status.json',
    type: 'statuspage',
  },
  {
    id: 'gemini',
    name: 'Gemini',
    category: 'AI',
    color: '#4285f4',
    logoDomain: 'gemini.google.com',
    statusPageUrl: 'https://status.cloud.google.com',
    apiUrl: 'https://status.cloud.google.com/incidents.json',
    type: 'google_cloud',
  },

  // --- Communication ---
  {
    id: 'slack',
    popular: true,
    name: 'Slack',
    category: 'Communication',
    color: '#611f69',
    statusPageUrl: 'https://status.slack.com',
    apiUrl: 'https://status.slack.com/api/v2.0.0/current',
    type: 'slack',
  },
  {
    id: 'zoom',
    popular: true,
    name: 'Zoom',
    category: 'Communication',
    color: '#2d8cff',
    statusPageUrl: 'https://status.zoom.us',
    apiUrl: 'https://status.zoom.us/api/v2/status.json',
    type: 'statuspage',
  },
  {
    id: 'discord',
    popular: true,
    name: 'Discord',
    category: 'Communication',
    color: '#7289da',
    logoDomain: 'discord.com',
    statusPageUrl: 'https://discordstatus.com',
    apiUrl: 'https://discordstatus.com/api/v2/status.json',
    type: 'statuspage',
  },
  {
    id: 'twilio',
    popular: true,
    name: 'Twilio',
    category: 'Communication',
    color: '#f22f46',
    statusPageUrl: 'https://status.twilio.com',
    apiUrl: 'https://status.twilio.com/api/v2/status.json',
    type: 'statuspage',
  },
  {
    id: 'webex',
    name: 'Webex',
    category: 'Communication',
    color: '#00b4e5',
    statusPageUrl: 'https://status.webex.com',
    apiUrl: 'https://status.webex.com/api/v2/status.json',
    type: 'statuspage',
  },
  {
    id: 'ringcentral',
    name: 'RingCentral',
    category: 'Communication',
    color: '#0073ae',
    statusPageUrl: 'https://status.ringcentral.com',
    apiUrl: 'https://status.ringcentral.com/api/v2/status.json',
    type: 'statuspage',
  },
  {
    id: 'vonage',
    name: 'Vonage',
    category: 'Communication',
    color: '#6d2ac7',
    statusPageUrl: 'https://status.vonage.com',
    apiUrl: 'https://status.vonage.com/api/v2/status.json',
    type: 'statuspage',
  },
  {
    id: 'telnyx',
    name: 'Telnyx',
    category: 'Communication',
    color: '#00c785',
    statusPageUrl: 'https://status.telnyx.com',
    apiUrl: 'https://status.telnyx.com/api/v2/status.json',
    type: 'statuspage',
  },
  {
    id: 'pusher',
    name: 'Pusher',
    category: 'Communication',
    color: '#300d4f',
    statusPageUrl: 'https://status.pusher.com',
    apiUrl: 'https://status.pusher.com/api/v2/status.json',
    type: 'statuspage',
  },
  {
    id: 'ably',
    name: 'Ably',
    category: 'Communication',
    color: '#ff5416',
    statusPageUrl: 'https://status.ably.com',
    apiUrl: 'https://status.ably.com/api/v2/status.json',
    type: 'statuspage',
  },

  // --- Project Management ---
  {
    id: 'asana',
    popular: true,
    name: 'Asana',
    category: 'Project Management',
    color: '#f06a6a',
    statusPageUrl: 'https://status.asana.com',
    apiUrl: 'https://status.asana.com/api/v2/status.json',
    type: 'statuspage',
    regionFilter: { exclude: ['Middle East', 'UAE', 'APAC', 'Asia Pacific'] },
  },
  {
    id: 'linear',
    popular: true,
    name: 'Linear',
    category: 'Project Management',
    color: '#5e6ad2',
    logoDomain: 'linear.app',
    statusPageUrl: 'https://linearstatus.com',
    apiUrl: 'https://linearstatus.com/api/v2/status.json',
    type: 'statuspage',
  },
  {
    id: 'jira',
    popular: true,
    name: 'Jira',
    category: 'Project Management',
    color: '#0052cc',
    logoDomain: 'atlassian.com/software/jira',
    statusPageUrl: 'https://jira-software.status.atlassian.com',
    apiUrl: 'https://jira-software.status.atlassian.com/api/v2/status.json',
    type: 'statuspage',
  },
  {
    id: 'notion',
    popular: true,
    name: 'Notion',
    category: 'Productivity',
    color: '#191919',
    statusPageUrl: 'https://status.notion.so',
    apiUrl: 'https://status.notion.so/api/v2/status.json',
    type: 'statuspage',
  },
  {
    id: 'monday',
    name: 'monday.com',
    category: 'Project Management',
    color: '#f62b54',
    statusPageUrl: 'https://status.monday.com',
    apiUrl: 'https://status.monday.com/api/v2/status.json',
    type: 'statuspage',
  },
  {
    id: 'airtable',
    popular: true,
    name: 'Airtable',
    category: 'Project Management',
    color: '#fcb400',
    statusPageUrl: 'https://status.airtable.com',
    apiUrl: 'https://status.airtable.com/api/v2/status.json',
    type: 'statuspage',
  },
  {
    id: 'clickup',
    name: 'ClickUp',
    category: 'Project Management',
    color: '#7b68ee',
    statusPageUrl: 'https://status.clickup.com',
    apiUrl: 'https://status.clickup.com/api/v2/status.json',
    type: 'statuspage',
  },
  {
    id: 'trello',
    name: 'Trello',
    category: 'Project Management',
    color: '#0052cc',
    logoDomain: 'trello.com',
    statusPageUrl: 'https://trello.status.atlassian.com',
    apiUrl: 'https://trello.status.atlassian.com/api/v2/status.json',
    type: 'statuspage',
  },
  {
    id: 'confluence',
    name: 'Confluence',
    category: 'Project Management',
    color: '#0052cc',
    logoDomain: 'confluence.atlassian.com',
    statusPageUrl: 'https://confluence.status.atlassian.com',
    apiUrl: 'https://confluence.status.atlassian.com/api/v2/status.json',
    type: 'statuspage',
  },
  {
    id: 'coda',
    name: 'Coda',
    category: 'Project Management',
    color: '#191919',
    statusPageUrl: 'https://status.coda.io',
    apiUrl: 'https://status.coda.io/api/v2/status.json',
    type: 'statuspage',
  },

  // --- Design & Collaboration ---
  {
    id: 'figma',
    popular: true,
    name: 'Figma',
    category: 'Design',
    color: '#f24e1e',
    statusPageUrl: 'https://status.figma.com',
    apiUrl: 'https://status.figma.com/api/v2/status.json',
    type: 'statuspage',
  },
  {
    id: 'miro',
    name: 'Miro',
    category: 'Design',
    color: '#ffd02f',
    statusPageUrl: 'https://status.miro.com',
    apiUrl: 'https://status.miro.com/api/v2/status.json',
    type: 'statuspage',
  },
  {
    id: 'loom',
    name: 'Loom',
    category: 'Design',
    color: '#625df5',
    logoDomain: 'loom.com',
    statusPageUrl: 'https://loom.status.atlassian.com',
    apiUrl: 'https://loom.status.atlassian.com/api/v2/status.json',
    type: 'statuspage',
  },

  // --- CRM & Marketing ---
  {
    id: 'hubspot',
    popular: true,
    name: 'HubSpot',
    category: 'CRM',
    color: '#ff7a59',
    statusPageUrl: 'https://status.hubspot.com',
    apiUrl: 'https://status.hubspot.com/api/v2/status.json',
    type: 'statuspage',
  },
  {
    id: 'braze',
    name: 'Braze',
    category: 'CRM',
    color: '#f26b26',
    logoDomain: 'braze.com',
    statusPageUrl: 'https://braze.statuspage.io',
    apiUrl: 'https://braze.statuspage.io/api/v2/status.json',
    type: 'statuspage',
  },
  {
    id: 'activecampaign',
    name: 'ActiveCampaign',
    category: 'CRM',
    color: '#356ae6',
    statusPageUrl: 'https://status.activecampaign.com',
    apiUrl: 'https://status.activecampaign.com/api/v2/status.json',
    type: 'statuspage',
  },

  // --- Email Marketing ---
  {
    id: 'mailchimp',
    popular: true,
    name: 'Mailchimp',
    category: 'Email Marketing',
    color: '#ffe01b',
    logoDomain: 'mailchimp.com',
    statusPageUrl: 'https://mailchimp.statuspage.io',
    apiUrl: 'https://mailchimp.statuspage.io/api/v2/status.json',
    type: 'statuspage',
  },
  {
    id: 'sendgrid',
    popular: true,
    name: 'SendGrid',
    category: 'Email Marketing',
    color: '#1a82e2',
    statusPageUrl: 'https://status.sendgrid.com',
    apiUrl: 'https://status.sendgrid.com/api/v2/status.json',
    type: 'statuspage',
  },
  {
    id: 'mailgun',
    name: 'Mailgun',
    category: 'Email Marketing',
    color: '#f06b26',
    statusPageUrl: 'https://status.mailgun.com',
    apiUrl: 'https://status.mailgun.com/api/v2/status.json',
    type: 'statuspage',
  },
  {
    id: 'brevo',
    name: 'Brevo',
    category: 'Email Marketing',
    color: '#0092ff',
    statusPageUrl: 'https://status.brevo.com',
    apiUrl: 'https://status.brevo.com/api/v2/status.json',
    type: 'statuspage',
  },
  {
    id: 'kit',
    name: 'Kit',
    category: 'Email Marketing',
    color: '#fb6970',
    statusPageUrl: 'https://status.kit.com',
    apiUrl: 'https://status.kit.com/api/v2/status.json',
    type: 'statuspage',
  },
  {
    id: 'customer-io',
    name: 'Customer.io',
    category: 'Email Marketing',
    color: '#5f34de',
    statusPageUrl: 'https://status.customer.io',
    apiUrl: 'https://status.customer.io/api/v2/status.json',
    type: 'statuspage',
  },

  // --- Customer Support ---
  {
    id: 'zendesk',
    popular: true,
    name: 'Zendesk',
    category: 'Customer Support',
    color: '#1f73b7',
    statusPageUrl: 'https://status.zendesk.com',
    type: 'link_only',
  },
  {
    id: 'intercom',
    popular: true,
    name: 'Intercom',
    category: 'Customer Support',
    color: '#286efa',
    statusPageUrl: 'https://www.intercomstatus.com',
    apiUrl: 'https://www.intercomstatus.com/api/v2/status.json',
    type: 'statuspage',
  },
  {
    id: 'gorgias',
    name: 'Gorgias',
    category: 'Customer Support',
    color: '#3b5ee8',
    statusPageUrl: 'https://status.gorgias.com',
    apiUrl: 'https://status.gorgias.com/api/v2/status.json',
    type: 'statuspage',
  },
  {
    id: 'helpscout',
    name: 'Help Scout',
    category: 'Customer Support',
    color: '#1292ee',
    statusPageUrl: 'https://status.helpscout.com',
    apiUrl: 'https://status.helpscout.com/api/v2/status.json',
    type: 'statuspage',
  },
  {
    id: 'drift',
    name: 'Drift',
    category: 'Customer Support',
    color: '#175dd8',
    statusPageUrl: 'https://status.drift.com',
    apiUrl: 'https://status.drift.com/api/v2/status.json',
    type: 'statuspage',
  },
  {
    id: 'livechat',
    name: 'LiveChat',
    category: 'Customer Support',
    color: '#ff5000',
    statusPageUrl: 'https://status.livechat.com',
    apiUrl: 'https://status.livechat.com/api/v2/status.json',
    type: 'statuspage',
  },

  // --- Infrastructure ---
  {
    id: 'github',
    popular: true,
    name: 'GitHub',
    category: 'Infrastructure',
    color: '#24292e',
    statusPageUrl: 'https://www.githubstatus.com',
    apiUrl: 'https://www.githubstatus.com/api/v2/status.json',
    type: 'statuspage',
  },
  {
    id: 'cloudflare',
    popular: true,
    name: 'Cloudflare',
    category: 'Infrastructure',
    color: '#f38020',
    statusPageUrl: 'https://www.cloudflarestatus.com',
    apiUrl: 'https://www.cloudflarestatus.com/api/v2/status.json',
    type: 'statuspage',
  },
  {
    id: 'digitalocean',
    name: 'DigitalOcean',
    category: 'Infrastructure',
    color: '#0080ff',
    statusPageUrl: 'https://status.digitalocean.com',
    apiUrl: 'https://status.digitalocean.com/api/v2/status.json',
    type: 'statuspage',
  },
  {
    id: 'linode',
    name: 'Linode',
    category: 'Infrastructure',
    color: '#00b050',
    statusPageUrl: 'https://status.linode.com',
    apiUrl: 'https://status.linode.com/api/v2/status.json',
    type: 'statuspage',
  },

  // --- Hosting ---
  {
    id: 'vercel',
    popular: true,
    name: 'Vercel',
    category: 'Hosting',
    color: '#000000',
    logoDomain: 'vercel.com',
    statusPageUrl: 'https://www.vercel-status.com',
    apiUrl: 'https://www.vercel-status.com/api/v2/status.json',
    type: 'statuspage',
  },
  {
    id: 'netlify',
    popular: true,
    name: 'Netlify',
    category: 'Hosting',
    color: '#00c7b7',
    logoDomain: 'netlify.com',
    statusPageUrl: 'https://www.netlifystatus.com',
    apiUrl: 'https://www.netlifystatus.com/api/v2/status.json',
    type: 'statuspage',
  },
  {
    id: 'render',
    name: 'Render',
    category: 'Hosting',
    color: '#46e3b7',
    statusPageUrl: 'https://status.render.com',
    apiUrl: 'https://status.render.com/api/v2/status.json',
    type: 'statuspage',
  },
  {
    id: 'flyio',
    name: 'Fly.io',
    category: 'Hosting',
    color: '#7b3ff2',
    statusPageUrl: 'https://status.flyio.net',
    apiUrl: 'https://status.flyio.net/api/v2/status.json',
    type: 'statuspage',
  },

  // --- Developer Tools ---
  {
    id: 'circleci',
    name: 'CircleCI',
    category: 'Developer Tools',
    color: '#343434',
    statusPageUrl: 'https://status.circleci.com',
    apiUrl: 'https://status.circleci.com/api/v2/status.json',
    type: 'statuspage',
  },
  {
    id: 'buildkite',
    name: 'Buildkite',
    category: 'Developer Tools',
    color: '#30f2a2',
    statusPageUrl: 'https://www.buildkitestatus.com',
    apiUrl: 'https://buildkitestatus.com/api/v2/status.json',
    type: 'statuspage',
  },
  {
    id: 'supabase',
    name: 'Supabase',
    category: 'Developer Tools',
    color: '#3ecf8e',
    statusPageUrl: 'https://status.supabase.com',
    apiUrl: 'https://status.supabase.com/api/v2/status.json',
    type: 'statuspage',
  },
  {
    id: 'launchdarkly',
    name: 'LaunchDarkly',
    category: 'Developer Tools',
    color: '#405bff',
    statusPageUrl: 'https://status.launchdarkly.com',
    apiUrl: 'https://status.launchdarkly.com/api/v2/status.json',
    type: 'statuspage',
  },
  {
    id: 'npm',
    name: 'npm',
    category: 'Developer Tools',
    color: '#cb3837',
    statusPageUrl: 'https://status.npmjs.org',
    apiUrl: 'https://status.npmjs.org/api/v2/status.json',
    type: 'statuspage',
  },
  {
    id: 'snyk',
    name: 'Snyk',
    category: 'Developer Tools',
    color: '#4c4a73',
    statusPageUrl: 'https://status.snyk.io',
    apiUrl: 'https://status.snyk.io/api/v2/status.json',
    type: 'statuspage',
  },
  {
    id: 'hashicorp',
    name: 'HashiCorp',
    category: 'Developer Tools',
    color: '#1f2b37',
    statusPageUrl: 'https://status.hashicorp.com',
    apiUrl: 'https://status.hashicorp.com/api/v2/status.json',
    type: 'statuspage',
  },
  {
    id: 'algolia',
    name: 'Algolia',
    category: 'Developer Tools',
    color: '#5468ff',
    statusPageUrl: 'https://status.algolia.com',
    apiUrl: 'https://status.algolia.com/api/v2/status.json',
    type: 'statuspage',
  },
  {
    id: 'cloudinary',
    name: 'Cloudinary',
    category: 'Developer Tools',
    color: '#3448c5',
    statusPageUrl: 'https://status.cloudinary.com',
    apiUrl: 'https://status.cloudinary.com/api/v2/status.json',
    type: 'statuspage',
  },
  {
    id: 'stream',
    name: 'Stream',
    category: 'Developer Tools',
    color: '#005fff',
    statusPageUrl: 'https://status.getstream.io',
    apiUrl: 'https://status.getstream.io/api/v2/status.json',
    type: 'statuspage',
  },

  // --- Monitoring & Observability ---
  {
    id: 'datadog',
    popular: true,
    name: 'Datadog',
    category: 'Monitoring',
    color: '#632ca6',
    statusPageUrl: 'https://status.datadoghq.com',
    apiUrl: 'https://status.datadoghq.com/api/v2/status.json',
    type: 'statuspage',
  },
  {
    id: 'newrelic',
    name: 'New Relic',
    category: 'Monitoring',
    color: '#008c99',
    statusPageUrl: 'https://status.newrelic.com',
    apiUrl: 'https://status.newrelic.com/api/v2/status.json',
    type: 'statuspage',
  },
  {
    id: 'sentry',
    popular: true,
    name: 'Sentry',
    category: 'Monitoring',
    color: '#362d59',
    statusPageUrl: 'https://status.sentry.io',
    apiUrl: 'https://status.sentry.io/api/v2/status.json',
    type: 'statuspage',
  },
  {
    id: 'grafana',
    name: 'Grafana Cloud',
    category: 'Monitoring',
    color: '#f46800',
    statusPageUrl: 'https://status.grafana.com',
    apiUrl: 'https://status.grafana.com/api/v2/status.json',
    type: 'statuspage',
  },

  // --- Security & Identity ---
  {
    id: '1password',
    name: '1Password',
    category: 'Security',
    color: '#1a8cff',
    statusPageUrl: 'https://status.1password.com',
    apiUrl: 'https://status.1password.com/api/v2/status.json',
    type: 'statuspage',
  },
  {
    id: 'duo',
    name: 'Duo Security',
    category: 'Security',
    color: '#6bbf4e',
    statusPageUrl: 'https://status.duo.com',
    apiUrl: 'https://status.duo.com/api/v2/status.json',
    type: 'statuspage',
  },

  // --- Data Platform ---
  {
    id: 'snowflake',
    name: 'Snowflake',
    category: 'Data Platform',
    color: '#29b5e8',
    statusPageUrl: 'https://status.snowflake.com',
    apiUrl: 'https://status.snowflake.com/api/v2/status.json',
    type: 'statuspage',
  },
  {
    id: 'segment',
    name: 'Segment',
    category: 'Data Platform',
    color: '#52bd95',
    statusPageUrl: 'https://status.segment.com',
    apiUrl: 'https://status.segment.com/api/v2/status.json',
    type: 'statuspage',
  },
  {
    id: 'fivetran',
    name: 'Fivetran',
    category: 'Data Platform',
    color: '#013cc5',
    statusPageUrl: 'https://status.fivetran.com',
    apiUrl: 'https://status.fivetran.com/api/v2/status.json',
    type: 'statuspage',
  },
  {
    id: 'dbt',
    name: 'dbt Cloud',
    category: 'Data Platform',
    color: '#ff694a',
    statusPageUrl: 'https://status.getdbt.com',
    apiUrl: 'https://status.getdbt.com/api/v2/status.json',
    type: 'statuspage',
  },
  {
    id: 'stitchdata',
    name: 'Stitch Data',
    category: 'Data Platform',
    color: '#2c6ec9',
    statusPageUrl: 'https://status.stitchdata.com',
    apiUrl: 'https://status.stitchdata.com/api/v2/status.json',
    type: 'statuspage',
  },
  {
    id: 'y42',
    name: 'Y42',
    category: 'Data Platform',
    color: '#0066cc',
    logoDomain: 'y42.com',
    statusPageUrl: 'https://y42.statuspage.io',
    apiUrl: 'https://y42.statuspage.io/api/v2/status.json',
    type: 'statuspage',
  },

  // --- Analytics ---
  {
    id: 'mixpanel',
    name: 'Mixpanel',
    category: 'Analytics',
    color: '#7856ff',
    statusPageUrl: 'https://status.mixpanel.com',
    apiUrl: 'https://status.mixpanel.com/api/v2/status.json',
    type: 'statuspage',
  },
  {
    id: 'amplitude',
    name: 'Amplitude',
    category: 'Analytics',
    color: '#1a2bff',
    statusPageUrl: 'https://status.amplitude.com',
    apiUrl: 'https://status.amplitude.com/api/v2/status.json',
    type: 'statuspage',
  },
  {
    id: 'hotjar',
    name: 'Hotjar',
    category: 'Analytics',
    color: '#ff3c00',
    statusPageUrl: 'https://status.hotjar.com',
    apiUrl: 'https://status.hotjar.com/api/v2/status.json',
    type: 'statuspage',
  },
  {
    id: 'fullstory',
    name: 'FullStory',
    category: 'Analytics',
    color: '#4b2e91',
    statusPageUrl: 'https://status.fullstory.com',
    apiUrl: 'https://status.fullstory.com/api/v2/status.json',
    type: 'statuspage',
  },
  {
    id: 'optimizely',
    name: 'Optimizely',
    category: 'Analytics',
    color: '#005cb9',
    statusPageUrl: 'https://status.optimizely.com',
    apiUrl: 'https://status.optimizely.com/api/v2/status.json',
    type: 'statuspage',
  },
  {
    id: 'pendo',
    name: 'Pendo',
    category: 'Analytics',
    color: '#ff4f00',
    statusPageUrl: 'https://status.pendo.io',
    apiUrl: 'https://status.pendo.io/api/v2/status.json',
    type: 'statuspage',
  },

  // --- Scheduling & Forms ---
  {
    id: 'calendly',
    name: 'Calendly',
    category: 'Scheduling',
    color: '#006bff',
    statusPageUrl: 'https://www.calendlystatus.com',
    apiUrl: 'https://www.calendlystatus.com/api/v2/status.json',
    type: 'statuspage',
  },
  {
    id: 'typeform',
    name: 'Typeform',
    category: 'Forms',
    color: '#262627',
    statusPageUrl: 'https://status.typeform.com',
    apiUrl: 'https://status.typeform.com/api/v2/status.json',
    type: 'statuspage',
  },
  {
    id: 'surveymonkey',
    name: 'SurveyMonkey',
    category: 'Forms',
    color: '#00bf6f',
    statusPageUrl: 'https://status.surveymonkey.com',
    apiUrl: 'https://status.surveymonkey.com/api/v2/status.json',
    type: 'statuspage',
  },

  // --- Social Media Management ---
  {
    id: 'buffer',
    name: 'Buffer',
    category: 'Social Media',
    color: '#168eea',
    statusPageUrl: 'https://status.buffer.com',
    apiUrl: 'https://status.buffer.com/api/v2/status.json',
    type: 'statuspage',
  },
  {
    id: 'hootsuite',
    name: 'Hootsuite',
    category: 'Social Media',
    color: '#143059',
    statusPageUrl: 'https://status.hootsuite.com',
    apiUrl: 'https://status.hootsuite.com/api/v2/status.json',
    type: 'statuspage',
  },
  {
    id: 'sproutsocial',
    name: 'Sprout Social',
    category: 'Social Media',
    color: '#59cb59',
    statusPageUrl: 'https://www.sproutsocialstatus.com',
    apiUrl: 'https://www.sproutsocialstatus.com/api/v2/status.json',
    type: 'statuspage',
  },

  // --- Storage & Files ---
  {
    id: 'dropbox',
    name: 'Dropbox',
    category: 'Storage',
    color: '#0061ff',
    statusPageUrl: 'https://status.dropbox.com',
    apiUrl: 'https://status.dropbox.com/api/v2/status.json',
    type: 'statuspage',
  },
  {
    id: 'box',
    name: 'Box',
    category: 'Storage',
    color: '#0075db',
    statusPageUrl: 'https://status.box.com',
    apiUrl: 'https://status.box.com/api/v2/status.json',
    type: 'statuspage',
  },

  // --- CMS & Content ---
  {
    id: 'contentful',
    name: 'Contentful',
    category: 'CMS',
    color: '#fae042',
    statusPageUrl: 'https://www.contentfulstatus.com',
    apiUrl: 'https://www.contentfulstatus.com/api/v2/status.json',
    type: 'statuspage',
  },
  {
    id: 'sanity',
    name: 'Sanity',
    category: 'CMS',
    color: '#f03e2f',
    statusPageUrl: 'https://status.sanity.io',
    apiUrl: 'https://status.sanity.io/api/v2/status.json',
    type: 'statuspage',
  },
  {
    id: 'ghost',
    name: 'Ghost',
    category: 'CMS',
    color: '#15171a',
    statusPageUrl: 'https://ghoststatus.org',
    apiUrl: 'https://ghoststatus.org/api/v2/status.json',
    type: 'statuspage',
  },

  // --- Streaming ---
  {
    id: 'twitch',
    name: 'Twitch',
    category: 'Streaming',
    color: '#9146ff',
    statusPageUrl: 'https://status.twitch.tv',
    apiUrl: 'https://status.twitch.tv/api/v2/status.json',
    type: 'statuspage',
  },
];

function getAllServices() {
  return services.map(({ apiUrl, ...rest }) => rest);
}

function getServiceById(id) {
  return services.find((s) => s.id === id) || null;
}

function getFullRegistry() {
  return services;
}

module.exports = { getAllServices, getServiceById, getFullRegistry };
